kind: Namespace
apiVersion: v1
metadata:
  name: apps-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-app
  namespace: apps-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-app
  template:
    metadata:
      labels:
        app: load-app
        instrument: beyla
    spec:
      containers:
        - name: load-app
          image: ghcr.io/gjpin/apps-demo-app:25.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - app-nodes  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - load-app
                - bff1
                - bff2
                - backend1
                - backend2
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps-demo
  name: load-app
  labels:
    app: load-app
spec:
  ports:
    - port: 8080
  selector:
    app: load-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff1
  namespace: apps-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff1
  template:
    metadata:
      labels:
        app: bff1
        instrument: beyla
    spec:
      containers:
        - name: bff1
          image: ghcr.io/gjpin/apps-demo-bff1:25.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - app-nodes  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - load-app
                - bff1
                - bff2
                - backend1
                - backend2
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps-demo
  name: bff1
  labels:
    app: bff1
spec:
  ports:
    - port: 8080
  selector:
    app: bff1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff2
  namespace: apps-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff2
  template:
    metadata:
      labels:
        app: bff2
        instrument: beyla
    spec:
      containers:
        - name: bff2
          image: ghcr.io/gjpin/apps-demo-bff2:25.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - app-nodes  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - load-app
                - bff1
                - bff2
                - backend1
                - backend2
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps-demo
  name: bff2
  labels:
    app: bff2
spec:
  ports:
    - port: 8080
  selector:
    app: bff2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: apps-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
        instrument: beyla
    spec:
      containers:
        - name: backend1
          image: ghcr.io/gjpin/apps-demo-backend1:25.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - app-nodes  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - load-app
                - bff1
                - bff2
                - backend1
                - backend2
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps-demo
  name: backend1
  labels:
    app: backend1
spec:
  ports:
    - port: 8080
  selector:
    app: backend1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  namespace: apps-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
        instrument: beyla
    spec:
      containers:
        - name: backend2
          image: ghcr.io/gjpin/apps-demo-backend2:25.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - app-nodes  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - load-app
                - bff1
                - bff2
                - backend1
                - backend2
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps-demo
  name: backend2
  labels:
    app: backend2
spec:
  ports:
    - port: 8080
  selector:
    app: backend2
